name: Something else
description: Need to open an issue that's not about Talks or Venues?
assignees:
  - 'Zahidul-Islam'
  - 'christian-bromann'
body:
    - type: markdown
      attributes:
        value: |
            Thanks so much for your interest in hosting SFNode! Let us know what's on your mind!
    - type: textarea
      attributes:
        label: I have some feedback!
      validations:
        required: true
